Version 0.0.47
A more object oriented approach

- Improved testing
- Added .vscode to .gitignore
- Improved README.md
- Added support for backend.tf
- Added providers as a meta argument
- Added some mock style testing

diff --git a/do/check-go-sort b/do/check-go-sort
--- a/do/check-go-sort
+++ b/do/check-go-sort
@@ -1,12 +1,15 @@
 #!/bin/bash
 # shellcheck disable=SC2005
 
-if ! grep '^func ' < main.go | sort -c; then
-  >&2 echo "ERROR: Functions are not in sorted order."
-  >&2 echo "**********"
-  >&2 echo "$(grep '^func ' < main.go 2>&1 | nl 2>&1   | sed -e 's/^/ACTUAL --- /')"
-  >&2 echo "**********"
-  >&2 echo "$(grep '^func ' < main.go 2>&1 | sort | nl 2>&1 | sed -e 's/^/EXPECTED - /')"
-  >&2 echo "**********"
-  exit 1
-fi
+for file in 'main.go' 'taho.go' 'proxy.go';
+do
+  if ! grep '^func ' < "$file" | sort -c; then
+    >&2 echo "ERROR: Functions are not in sorted order."
+    >&2 echo "**********"
+    >&2 echo "$(grep '^func ' < "$file" 2>&1 | sort | nl 2>&1 | sed -e 's/^/EXPECTED - /')"
+    >&2 echo "**********"
+    >&2 echo "$(grep '^func ' < "$file" 2>&1 | nl 2>&1   | sed -e 's/^/ACTUAL --- /')"
+    >&2 echo "**********"
+    exit 1
+  fi
+done
