Version 0.0.25
- Added sorting for nested block types
- Extensive refactoring and code improvements

diff --git a/do/release b/do/release
--- a/do/release
+++ b/do/release
@@ -1,4 +1,14 @@
 #!/bin/bash
+set -e
+
+do/check-go-sort
+
+status="$(git status -s)"
+if [ -n "$status" ]; then
+  >&2 echo "ERROR: Unable to release due to git status."
+  >&2 echo "$status"
+  exit 1
+fi
 
 rm -rf release
 mkdir release
